### ISSUE TITLE
Shall we provide the release for 2.11+ related whls?

### ISSUE THREAD

**Issue by Gnosnay** [diyor28/tf-aarch64#17]
for now, we only support tensorflow 2.10, and no where to download higher version.
May i know how to build it on my own or is that possible to provide the assets for 2.11+ version?

**Comment by diyor28** [comment]
@Yansongsongsong I think the reason 2.11+ was skipped is because versions after 2.11 come with prebuilt aarch64 whls

**Comment by Gnosnay** [comment]
> @Yansongsongsong I think the reason 2.11+ was skipped is because versions after 2.11 come with prebuilt aarch64 whls

just knew it now... thank you so much!!!
