### ISSUE TITLE
generated code is out of date and must be regenerated with protoc >= 3.19.0.

### ISSUE THREAD

**Issue by AseiSugiyama** [diyor28/tf-aarch64#2]
## Environment and target

- Python Version: 3.8
- TensorFlow Version: 2.8.0

## Error message

This error occurs at `#17 [tf-install 5/5] RUN python test.py` step

```
#17 0.791 If you cannot immediately regenerate your protos, some other possible workarounds are:
#17 0.791  1. Downgrade the protobuf package to 3.20.x or lower.
#17 0.791  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
#17 0.791 
#17 0.791 More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
## Full log

[tf280_py38.txt](https://github.com/diyor28/tf-aarch64/files/10192101/tf280_py38.txt)

**Comment by diyor28** [comment]
Take a look [here](https://github.com/diyor28/tf-docker-m1/issues/1#issuecomment-1255077874). Can you confirm this is the same as this issue?

**Comment by AseiSugiyama** [comment]
I guess so, the message is strictly the same.

**Comment by diyor28** [comment]
I did some research and the problem is not the build itself. I guess TensorFlow or dependency of TensorFlow specifies the minimum version of protobuf, but not the maximum. And the best solution is just manually to install protobuf==3.20.x as suggested in the link I provided you.

**Comment by diyor28** [comment]
So something like https://github.com/diyor28/tf-aarch64/pull/10
