### ISSUE TITLE
gcc: fatal error: Killed signal terminated program cc1plus

### ISSUE THREAD

**Issue by AseiSugiyama** [diyor28/tf-aarch64#3]
## Environment and target

- Python: 3.9
- TensorFlow: 2.8.0

## Error message

`gcc: fatal error` occurs at `#12 [tf-build 8/9] RUN bazel build --config=opt -c opt //tensorflow/tools/pi...` step

```
#12 2.149 ERROR: /tensorflow/tensorflow/compiler/mlir/tensorflow/BUILD:573:11: Compiling tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 151 argument(s) skipped)
#12 2.149 gcc: fatal error: Killed signal terminated program cc1plus
#12 2.149 compilation terminated.
#12 2.153 Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

## Full log

[tf280_py39.txt](https://github.com/diyor28/tf-aarch64/files/10192139/tf280_py39.txt)

**Comment by AseiSugiyama** [comment]
I guess this can be caused by no space left in my local storage. Let me try this again.

**Comment by diyor28** [comment]
I think so as well, considering the error happened so late in the build process

**Comment by diyor28** [comment]
@AseiSugiyama Can you give an update if rebuilding solved the issue?
