### ISSUE TITLE
fatal error: immintrin.h: No such file or directory

### ISSUE THREAD

**Issue by AseiSugiyama** [diyor28/tf-aarch64#6]
## Environment and target

- Python: 3.8, 3.9, 3.10, 3.11
- TFX: 1.10

## Error message

This error raised at `#15 [tfx-build 10/15] RUN chmod +x replace_commits.sh && ./replace_commits.s...` step.

```
#15 237.6 ERROR: /root/.cache/bazel/_bazel_root/69d415f69592c20e8fa96228da1bfb1a/external/arrow/BUILD.bazel:36:11: Compiling cpp/src/arrow/compute/exec/key_map_avx2.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 39 argument(s) skipped)
#15 237.6 
#15 237.6 Use --sandbox_debug to see verbose messages from the sandbox
#15 237.6 external/arrow/cpp/src/arrow/compute/exec/key_map_avx2.cc:18:10: fatal error: immintrin.h: No such file or directory
#15 237.6    18 | #include <immintrin.h>
#15 237.6       |          ^~~~~~~~~~~~~
#15 237.6 compilation terminated.
#15 238.0 Target //tfx_bsl:move_generated_files failed to build
```

## Full log

- [tfx1100_py38.txt](https://github.com/diyor28/tf-aarch64/files/10192442/tfx1100_py38.txt)
- [tfx1100_py39.txt](https://github.com/diyor28/tf-aarch64/files/10192666/tfx1100_py39.txt)
- [tfx1100_py310.txt](https://github.com/diyor28/tf-aarch64/files/10192668/tfx1100_py310.txt)
- [tfx1100_py311.txt](https://github.com/diyor28/tf-aarch64/files/10192671/tfx1100_py311.txt)

**Comment by diyor28** [comment]
@AseiSugiyama Please take a look at this PR and verify it works on your machine https://github.com/diyor28/tf-aarch64/pull/11. After that let me know if we can close this issue

**Comment by AseiSugiyama** [comment]
Okay, let me check this.

**Comment by AseiSugiyama** [comment]
Great! I tested #11 and it works!

Let me explain the way to test the TFDV builds.

## Setup

I changed the locations of the artifacts (logs and wheel files) to avoid disabling the security feature of macOS. I used [this workaround](https://github.com/diyor28/tf-aarch64/pull/1).

## Build result

### Passed

- Python: 3.8, 3.9
- TFX: 1.9.0, 1.10.0 (also, 1.10.x)

### Failed

- Python: 3.10
- TFX: 1.9.0, 1.10.0

This is another issue we should solve. Let's skip it now.

## Test wheel file

### Setup container

I used `python:3.8` for testing environment.

```console
TFDV=tensorflow_data_validation-1.10.0-cp38-cp38-linux_aarch64.whl
TFX_BSL=tfx_bsl-1.10.1-cp38-cp38-linux_aarch64.whl
docker run -v /tmp/tf_aarch64/volumes/builds/$TFDV:/$TFDV -v /tmp/tf_aarch64/volumes/builds/$TFX_BSL:/$TFX_BSL -it python:3.8 bash
```

Then, I installed wheel files as followings;

```console
pip install -U pip
pip install tfx_bsl-1.10.1-cp38-cp38-linux_aarch64.whl
pip install tensorflow_data_validation-1.10.0-cp38-cp38-linux_aarch64.whl
```

Also, I update `numpy` because we use `numpy` with C API version 0x10 in the build environment. C API 0x10 means version 1.23+ (currently)

```console
pip install numpy~=1.23
```

We can check the relationship between `numpy` versions and C API versions of `numpy` from [here](https://github.com/numpy/numpy/blob/main/numpy/core/code_generators/cversions.txt). For more detail, check [this comment](https://github.com/tensorflow/tensorflow/issues/57106).

Note: I cannot use wheel files of Python 3.8 and TFX 1.10 because of the dependency. (TFDV 1.10 requires tfx-bsl 1.10.1+)

### Test file and test methods

I used a test dataset (subset of taxi dataset) and `tfdv.generate_statistics_from_csv()` to test the wheel file as followings.

```console
curl https://gist.githubusercontent.com/kennysong/b9f3ffe1299d331cdde92c46504a5ea1/raw/832b6a958dec86ce313d5be3033e281a87c21847/taxi_2020_test_converted.csv > taxi.csv
python -c "import tensorflow_data_validation as tfdv; print(tfdv.generate_statistics_from_csv('taxi.csv'))"
```

**Comment by diyor28** [comment]
@AseiSugiyama Great to hear! I will update tfdv1.10.0 build to use tfx1.10.1 and numpy 1.23+
